### ISSUE TITLE
links

### ISSUE THREAD

**Issue by hello1234316** [Slime1207/DiscordOTF--PollFile#3]
# DONE

https://dis.cord.gifts/c/FUnMtvak2VJ​​BvNHB

https://dlscord.life/zrx8ubzYZIStKs0u

https://l.discord.ski/AFgOGOTukVCGEbd6

https://discordgift.site/N60cQp0SS6AZGW7u

https://discordgift.site/c/DGMbb8XP1keIkRmG

https://discordgift.site/games/redeem/nIvSuifvln1209ZF

https://discordgift.site/store/en-US/p/discord--discord-nitro

https://dis.cord.gifts/c/J9UjfAfSqJsZBjXz

**Comment by Slime1207** [comment]
Ok... 因为我只拿字眼
所以里面有 dis.cord.gifts , discord.life , l.discord.ski , discordgift.site
感谢你的建议哦UwU

**Comment by hello1234316** [comment]
but some group may send the real discord nitro gift but your delete it , what will it happen?

**Comment by Slime1207** [comment]
已增加

**Comment by hello1234316** [comment]
![Uploading IMG-20210910-WA0031.jpg…]()

**Comment by Slime1207** [comment]
> but some group may send the real discord nitro gift but your delete it , what will it happen?

对于这个问题 我直接拿一个Discord Link来说好了
discord.gift/never-wanna-give-u-up (例如
机器人本身只会对 dis.cord.gifts;dQw4w9WgXcQ;dlscord.com;discordapp.click;discord.life;l.discord.ski;discordgift.site 这几个字眼 ( 用;分开 ) 有反应
例如说我的朋友发了一个 Link : discord.gift/never-wanna-give-u-up
里面没有任何一个字眼与 discord/gift 对上 , 所以不会造成所谓的假删除事件...

**Comment by Slime1207** [comment]
如果真的不幸删掉了 我也会看到
总之 , 极小可能会被删掉 :>

**Comment by hello1234316** [comment]
🛐🛐🛐🛐🛐🛐🛐🛐🛐🛐🛐🛐

**Comment by Slime1207** [comment]
#### Closing Issue...
